/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.border.TitledBorder;
import util.RelatoryType;

/**
 *
 * @author Wallace Alves Esteves Manzano <wallace.manzano at usp.br>
 */
public class RelatoryPanel extends javax.swing.JPanel {
    String[] buttons = {"Cartões Vencidos", "Histórico Funcionário", "Frete", "Vendas por Ano", "Produto Mais Vendidos por Semestre", 
	"Produtos Mais Vendidos por Venda", "Venda por País"};
    final RelatoryType[] rt = {RelatoryType.CLIENTE_CARTAO, RelatoryType.HISTORICO_FUNCIONARIOS, RelatoryType.DADOS_FRETE, 
	RelatoryType.TODO, RelatoryType.TODO, RelatoryType.TODO, RelatoryType.TODO};
    /**
     * Creates new form MainPanelFull
     */
    public RelatoryPanel() {
	initComponents();
	setSize(200, 200);
	this.setBorder(new TitledBorder("Relatórios"));
	setLayout(new GridLayout(2, 4, 20, 20));
	setPreferredSize(new Dimension(getWidth(), 100));
	
	JButton b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Cartões Vencidos</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.CLIENTE_CARTAO);
		f.setVisible(true);
	    }
	});
	add(b);
	
	
	b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Histórico Funcionário</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.HISTORICO_FUNCIONARIOS);
		f.setVisible(true);
	    }
	});
	add(b);
		
	
	b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Frete</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.DADOS_FRETE);
		f.setVisible(true);
	    }
	});
	add(b);
	
	
	b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Vendas por Ano</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.VENDAS_ANO);
		f.setVisible(true);
	    }
	});
	add(b);
	
	
	b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Produto Mais Vendidos por Semestre</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.PRODUTOS_SEMESTRE);
		f.setVisible(true);
	    }
	});
	add(b);
	
	
	b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Par de Produtos Mais Vendidos por Venda</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.TODO);
		f.setVisible(true);
	    }
	});
	add(b);
	
	
	b = new JButton();
	b.setText("<html><div style='text-align: center;'><p style=\"width:120px\">Venda por País</p></div></html>");
	
	b.addActionListener(new java.awt.event.ActionListener() {

	    @Override
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		JFrame f = new RelatoryFrame(RelatoryType.VENDAS_POR_PAIS);
		f.setVisible(true);
	    }
	});
	add(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(840, 496));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
